version: '3'

services:
  upload:
    container_name: upload-service
    ports:
      - 3000:3000
    build:
      context: .
    environment:
      AWS_S3_BUCKET_NAME:
      AWS_S3_REGION:
      AWS_S3_SECRET_ACCESS_KEY:
      AWS_S3_ACCESS_KEY_ID:
      URL_PUBLIC:
    networks:
      - 200lab

  frontend:
    container_name: frontend
    ports:
      - 80:80
    build:
      context: ./fe
    networks:
      - 200lab

networks:
  200lab:
